[main]
font=JetBrainsMono Nerd Font:size=14
prompt="❯  "
icon-theme=Papirus-Dark
width=25
horizontal-pad=20
vertical-pad=10
inner-pad=5

# Настройка обводки (Зелёный Gruvbox @color10)
border-width=2
border-radius=12

[colors]
# Фон: #282828, Текст: #EBDBB2
background=282828ff
text=ebdbb2ff
# Выделение (Match): Желтый #FABD2F
match=fabd2fff
# Выбранный пункт: Фон #3c3836 (Lighter background), Текст #B8BB26 (Зелёный)
selection=3c3836ff
selection-text=b8bb26ff
selection-match=fabd2fff
# Та самая ЗЕЛЁНАЯ обводка (#B8BB26)
border=b8bb26ff

[border]
width=2
radius=12
